[project]
name = "bsky-followers"
version = "0.1.0"
description = "check your Bluesky followers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "atproto",
    "prefect@git+https://github.com/PrefectHQ/prefect.git@main",
]
